# fly.toml app configuration file generated for gateway-dawn-wildflower-3519 on 2025-06-03T10:18:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gateway-dawn-wildflower-3519'
primary_region = 'waw'

[env]
  KEYCLOAK_URL = "https://euc1.auth.ac/auth"
  KEYCLOAK_REALM = "general-auth"
  KEYCLOAK_CLIENT_ID = "api-client"
  KEYCLOAK_CLIENT_SECRET = "XVLTtJKNr7GSqrSGMvAMGwv3PMfN0NqW"
  PORT = "8080"
  AUTH_SERVICE_URL="https://auth-service-still-silence-9406.fly.dev"

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
