services:
  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: ./Dockerfile
    branch: new-master
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: AUTH_SERVICE_URL
        value: "https://user-service-nest-1.onrender.com"
      - key: EXPRESS_AUTH_SERVICE_URL
        value: "https://auth-service-still-silence-9406.fly.dev"
      - key: CAR_SERVICE_URL
        value: "https://car-service-jiwj.onrender.com"
      - key: JWT_SECRET
        value: "dev_access_secret"                    # Add your JWT secret
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
